##### Tensors:
Tensors can be considered as a general representation for multidimensional arrays

In [10]:
import numpy as np
import tensorflow as tf

In [11]:
# rank = axes = ndim
# rank-0 tensors
x_0 = np.array(12)
print(x_0.shape)
print(x_0.ndim)

# rank-1 tensors
x_1 = np.array([1, 2, 3, 4])
print(x_1.shape)
print(x_1.ndim)

# rank-2 tensors
x_2 = np.array([[1, 2], [3, 4]])
print(x_2.shape)
print(x_2.ndim)

# rank-3 tensors
x_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8,]]])
print(x_3.shape)
print(x_3.ndim)

()
0
(4,)
1
(2, 2)
2
(2, 2, 2)
3


In [12]:
# output = relu(dot(input, w) + b)
# What does ReLU do:
# if dot product is < 0 return 0 else output
def relu_function(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    
    return x

x = np.array([[1, 2, 3], [4, 5, 6]])
print(relu_function(x))

# NOTE: using numpy
# z = x + y
# z = np.maximum(z, 0)

[[1 2 3]
 [4 5 6]]


In [13]:
# what is broadcasting
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = np.dot(x, y)
print(z)

32


In [14]:
# dot product between a vector and a matrix
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
z = np.dot(x, y)
print(x.shape)
print(y.shape)
print(z)
print(z.shape)

(1, 3)
(3, 3)
[[48 54 60]]
(1, 3)


In [15]:
# tensor reshaping
x = np.array([[1, 2,], [3, 4], [5, 6]])
print(x.shape)

x = x.reshape((6, 1))
print(x)
print(x.shape)
x = x.reshape((2, 3))
print(x)
print(x.shape)

(3, 2)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [16]:
# Automatic differentiation:
# Capability or obtaining gradients on any number of tensor operations that are differentiable

# Stores tensor operations in a form of computational graph
x = tf.Variable(2.0)

with tf.GradientTape() as tape:
    # NOTE: using the calculus power rule
    # NOTE: taking the derivative means taking the slope of the function at a given point
    y = 3 * x ** 4
    # NOTE: using the tape to calculate the gradient of the output
    dy_dx = tape.gradient(y, x)

print(dy_dx)

tf.Tensor(96.0, shape=(), dtype=float32)


In [19]:
# calculating gradients on a list of variables
# variables are mutable objects
w = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2, )))
x = tf.random.uniform((2, 2))

with tf.GradientTape() as tape:
    y = tf.matmul(x, w) + b
    # gradients of y with respect to "w" and "b"
    grad_of_y = tape.gradient(y, [w, b])
    print(grad_of_y)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.15209198, 0.15209198],
       [0.59820557, 0.59820557]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]
